# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e36ddb9649d419e0920581a201ffceae819d3fa8e84349c1051fb5d6c40a31b6613a0df877fb4874c96955d36b5fb9f785f5b5569d6f9078c4096bf539bcbccf

test:
  secret_key_base: 59dbe28dc9d04c24e7a06e5e579165140a4f29a2fa410932f18e734b904a56385cc381cf16ae3cd0a9656d9ebc2cf6d6567e4f513831efbf072697049331cbfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
